# Generated by Django 2.2.4 on 2022-08-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mfsb',
        ),
    ]
