# Generated by Django 2.2.4 on 2022-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0002_delete_mfsb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mfsb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('values', models.FloatField(blank=True, db_column='Values', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('check', models.BooleanField(db_column='Check')),
            ],
            options={
                'db_table': 'mfsb',
                'managed': False,
            },
        ),
    ]
