# Generated by Django 2.2.4 on 2022-10-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=160, verbose_name='Наименование')),
                ('sn', models.CharField(default=' ', max_length=60, verbose_name='Серийный номер')),
                ('descr', models.CharField(default=' ', max_length=100, verbose_name='descr')),
                ('origin', models.CharField(default=' ', max_length=100, verbose_name='origin')),
            ],
            options={
                'verbose_name': 'датчик',
                'verbose_name_plural': 'датчики',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TagDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, verbose_name='Время отметки')),
                ('accuracy', models.IntegerField()),
                ('kinematic', models.IntegerField()),
                ('le_status', models.CharField(default=' ', max_length=60, verbose_name='Статус')),
                ('motion', models.CharField(default=' ', max_length=60, verbose_name='motion')),
                ('solution', models.CharField(default=' ', max_length=60, verbose_name='solution')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eps.Tag', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'отметка',
                'verbose_name_plural': 'отметки',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='eps_tag_name_e51b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='tagdate',
            index=models.Index(fields=['tag'], name='eps_tagdate_tag_id_ecfebf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tagdate',
            unique_together={('tag', 'time')},
        ),
    ]
