# Generated by Django 2.2.4 on 2022-10-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0002_auto_20221025_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagdate',
            name='seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tagdate',
            name='source',
            field=models.CharField(default=' ', max_length=60, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='tagdate',
            name='x',
            field=models.FloatField(default=0.0, verbose_name='x'),
        ),
        migrations.AddField(
            model_name='tagdate',
            name='y',
            field=models.FloatField(default=0.0, verbose_name='y'),
        ),
        migrations.AddField(
            model_name='tagdate',
            name='z',
            field=models.FloatField(default=0.0, verbose_name='z'),
        ),
    ]
