# Generated by Django 2.2.4 on 2022-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0003_auto_20221025_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='le_status',
            field=models.CharField(default=' ', max_length=60, verbose_name='Статус'),
        ),
    ]
