# Generated by Django 2.2.4 on 2022-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0004_tag_le_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='x',
            field=models.FloatField(default=0.0, verbose_name='x'),
        ),
        migrations.AddField(
            model_name='tag',
            name='y',
            field=models.FloatField(default=0.0, verbose_name='y'),
        ),
        migrations.AddField(
            model_name='tag',
            name='z',
            field=models.FloatField(default=0.0, verbose_name='z'),
        ),
    ]
