# Generated by Django 2.2.4 on 2022-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0005_auto_20221025_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rls_id', models.CharField(default=' ', max_length=160, verbose_name='id rls')),
                ('sn', models.CharField(default=' ', max_length=60, verbose_name='Серийный номер')),
                ('origin', models.CharField(default=' ', max_length=100, verbose_name='origin')),
                ('disabled', models.BooleanField(default=False, verbose_name='disabled')),
                ('descr', models.CharField(default=' ', max_length=100, verbose_name='descr')),
                ('label', models.CharField(default=' ', max_length=100, verbose_name='label')),
                ('x', models.FloatField(default=0.0, verbose_name='x')),
                ('y', models.FloatField(default=0.0, verbose_name='y')),
                ('z', models.FloatField(default=0.0, verbose_name='z')),
                ('device_type', models.CharField(default=' ', max_length=50, verbose_name='device_type')),
                ('status', models.CharField(default=' ', max_length=20, verbose_name='status')),
                ('ip_address', models.CharField(default=' ', max_length=20, verbose_name='ip_address')),
                ('coap_resource', models.CharField(default=' ', max_length=20, verbose_name='coap_resource')),
                ('subscribed', models.BooleanField(default=False, verbose_name='subscribed')),
                ('message_time', models.DateTimeField(blank=True, verbose_name='message_time')),
                ('status_time', models.DateTimeField(blank=True, verbose_name='status_time')),
                ('total_packets', models.IntegerField(default=0)),
                ('invalid_packets', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'анкер',
                'verbose_name_plural': 'анкера',
                'ordering': ('label',),
            },
        ),
        migrations.AddIndex(
            model_name='anchors',
            index=models.Index(fields=['label'], name='eps_anchors_label_e816e3_idx'),
        ),
    ]
