# Generated by Django 2.2.4 on 2022-09-04 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
                ('name', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='ФИО')),
                ('block', models.BooleanField(blank=True, default=False, verbose_name='Заблокирован')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Пользователь'), (1, 'Администратор'), (2, 'Администратор системы')], default=0, verbose_name='Роль пользователя')),
                ('api_client', models.BooleanField(blank=True, default=False, verbose_name='api client')),
                ('isredonly', models.BooleanField(blank=True, default=False, verbose_name='Только просмотр')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
