# Generated by Django 2.2 on 2023-02-27 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_auto_20221123_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default=' ', max_length=160, verbose_name='ТЭГ')),
                ('position', models.CharField(blank=True, default=' ', max_length=20, verbose_name='Позиция')),
                ('name', models.CharField(default=' ', max_length=160, verbose_name='Наименование')),
                ('value', models.IntegerField(blank=True, choices=[(0, 'нет связи (блокировка выведена)'), (1, 'блокировка активна')], default=0, verbose_name='Активность')),
                ('connect_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Последнее подключение')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'датчик блокировки',
                'verbose_name_plural': 'датчики блокировок',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlockIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Время показаний')),
                ('value', models.IntegerField(blank=True, choices=[(0, 'нет связи (блокировка выведена)'), (1, 'блокировка активна')], default=0, verbose_name='Активность')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='block.BlockSensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'показание датчика',
                'verbose_name_plural': 'показания датчиков',
                'ordering': ('sensor',),
            },
        ),
        migrations.AddIndex(
            model_name='blocksensor',
            index=models.Index(fields=['tag'], name='block_block_tag_9ac819_idx'),
        ),
        migrations.AddIndex(
            model_name='blocksensor',
            index=models.Index(fields=['name'], name='block_block_name_d194ef_idx'),
        ),
        migrations.AddIndex(
            model_name='blocksensor',
            index=models.Index(fields=['tag', 'name'], name='block_block_tag_0c33f2_idx'),
        ),
        migrations.AddIndex(
            model_name='blockindicators',
            index=models.Index(fields=['sensor'], name='block_block_sensor__6f1907_idx'),
        ),
        migrations.AddIndex(
            model_name='blockindicators',
            index=models.Index(fields=['date_time', 'sensor'], name='block_block_date_ti_c0d7ca_idx'),
        ),
    ]
