# Generated by Django 2.2.4 on 2023-02-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blockindicators',
            name='block_block_sensor__6f1907_idx',
        ),
    ]
