# Generated by Django 2.2.4 on 2023-03-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20230228_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=150, null=True)),
                ('values', models.FloatField(blank=True, db_column='Values', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('check', models.BooleanField(db_column='Check')),
            ],
            options={
                'verbose_name': 'Блокировки',
            },
        ),
    ]
