# Generated by Django 2.2 on 2023-03-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='check',
            field=models.BooleanField(blank=True, db_column='Check', default=False, null=True),
        ),
    ]
