# Generated by Django 2.2.4 on 2023-01-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codebolid',
            options={'ordering': ('name',), 'verbose_name': 'Код БОЛИД', 'verbose_name_plural': 'Коды БОЛИД'},
        ),
    ]
