# Generated by Django 2.2.4 on 2023-01-19 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221123_0925'),
        ('fp', '0002_auto_20230119_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='FpSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default=' ', max_length=160, verbose_name='ТЭГ')),
                ('name', models.CharField(default=' ', max_length=160, verbose_name='Наименование')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('connect_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Последнее подключение')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fp.CodeBolid', verbose_name='Код')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'датчик',
                'verbose_name_plural': 'датчики',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FpIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Время показаний')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fp.CodeBolid', verbose_name='Код')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fp.FpSensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'показание датчика',
                'verbose_name_plural': 'показания датчиков',
                'ordering': ('sensor',),
            },
        ),
        migrations.AddIndex(
            model_name='fpsensor',
            index=models.Index(fields=['tag'], name='fp_fpsensor_tag_2e8d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='fpsensor',
            index=models.Index(fields=['name'], name='fp_fpsensor_name_20fd67_idx'),
        ),
        migrations.AddIndex(
            model_name='fpsensor',
            index=models.Index(fields=['tag', 'name'], name='fp_fpsensor_tag_066f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='fpindicators',
            index=models.Index(fields=['sensor'], name='fp_fpindica_sensor__0c7f88_idx'),
        ),
        migrations.AddIndex(
            model_name='fpindicators',
            index=models.Index(fields=['date_time', 'sensor'], name='fp_fpindica_date_ti_7298a0_idx'),
        ),
    ]
