# Generated by Django 2.2.4 on 2023-01-19 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_auto_20221123_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScadaSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default=' ', max_length=160, verbose_name='ТЭГ')),
                ('name', models.CharField(default=' ', max_length=160, verbose_name='Наименование')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('value', models.FloatField(blank=True, default=0.0, verbose_name='Показание')),
                ('connect_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Последнее подключение')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'датчик',
                'verbose_name_plural': 'датчики',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ScadaIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Время показаний')),
                ('value', models.FloatField(default=0.0, verbose_name='Показание')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scada.ScadaSensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'показание датчика',
                'verbose_name_plural': 'показания датчиков',
                'ordering': ('sensor',),
            },
        ),
        migrations.AddIndex(
            model_name='scadasensor',
            index=models.Index(fields=['tag'], name='scada_scada_tag_58c7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='scadasensor',
            index=models.Index(fields=['name'], name='scada_scada_name_744b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='scadasensor',
            index=models.Index(fields=['tag', 'name'], name='scada_scada_tag_12cb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='scadaindicators',
            index=models.Index(fields=['sensor'], name='scada_scada_sensor__d286af_idx'),
        ),
        migrations.AddIndex(
            model_name='scadaindicators',
            index=models.Index(fields=['date_time', 'sensor'], name='scada_scada_date_ti_f8e0ab_idx'),
        ),
    ]
