# Generated by Django 2.2.4 on 2023-01-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scadasensor',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Zone', verbose_name='Зона'),
        ),
    ]
