# Generated by Django 2.2.4 on 2023-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0002_auto_20230119_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='scadasensor',
            name='position',
            field=models.CharField(blank=True, default=' ', max_length=20, verbose_name='Позиция'),
        ),
    ]
