# Generated by Django 2.2.4 on 2023-02-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0003_scadasensor_position'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scadasensor',
            index=models.Index(fields=['position'], name='scada_scada_positio_218e70_idx'),
        ),
    ]
