# Generated by Django 2.2.4 on 2023-02-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0004_auto_20230220_1316'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scadaindicators',
            name='scada_scada_sensor__d286af_idx',
        ),
    ]
