# Generated by Django 2.2.4 on 2022-09-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcsIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Время показаний')),
                ('value', models.IntegerField(default=0, verbose_name='Показание')),
            ],
            options={
                'verbose_name': 'показание датчика',
                'verbose_name_plural': 'показания датчиков',
                'ordering': ('sensor',),
            },
        ),
        migrations.CreateModel(
            name='AcsSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=60, verbose_name='Наименование')),
                ('critical_value', models.IntegerField(default=0, verbose_name='Критически допустимое значение')),
                ('critical_type', models.CharField(choices=[('max', 'Максимальный'), ('min', 'Минимальный')], default=1, max_length=3, verbose_name='Тип')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('value', models.IntegerField(default=0, verbose_name='Показание')),
                ('comments', models.TextField(blank=True, default=' ', max_length=1001, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'датчик',
                'verbose_name_plural': 'датчики',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='acssensor',
            index=models.Index(fields=['name'], name='acs_acssens_name_41e530_idx'),
        ),
        migrations.AddField(
            model_name='acsindicators',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acs.AcsSensor', verbose_name='Датчики'),
        ),
        migrations.AddIndex(
            model_name='acsindicators',
            index=models.Index(fields=['date_time', 'sensor'], name='acs_acsindi_date_ti_54a518_idx'),
        ),
    ]
