# Generated by Django 2.2.4 on 2022-03-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Показание'),
        ),
    ]
