# Generated by Django 2.2.4 on 2022-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='tag',
            field=models.CharField(default=' ', max_length=160, verbose_name='ТЭГ'),
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='name',
            field=models.CharField(default=' ', max_length=160, verbose_name='Наименование'),
        ),
        migrations.AddIndex(
            model_name='acssensor',
            index=models.Index(fields=['tag'], name='acs_acssens_tag_bf37f9_idx'),
        ),
        migrations.AddIndex(
            model_name='acssensor',
            index=models.Index(fields=['tag', 'name'], name='acs_acssens_tag_ce0d49_idx'),
        ),
    ]
