# Generated by Django 2.2.4 on 2022-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0002_auto_20220904_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsindicators',
            name='value',
            field=models.FloatField(default=0.0, verbose_name='Показание'),
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='value',
            field=models.FloatField(default=0.0, verbose_name='Показание'),
        ),
    ]
