# Generated by Django 2.2.4 on 2022-09-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0003_auto_20220904_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='value',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Показание'),
        ),
    ]
