# Generated by Django 2.2.4 on 2022-09-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0004_auto_20220904_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='critical_value',
            field=models.FloatField(default=0.0, verbose_name='Критически допустимое значение'),
        ),
    ]
