# Generated by Django 2.2.4 on 2022-09-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0005_auto_20220904_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='unit',
            field=models.CharField(default=' ', max_length=10, verbose_name='Ед.измерения'),
        ),
    ]
