# Generated by Django 2.2.4 on 2022-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0006_acssensor_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='max_value',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Максимальное значение'),
        ),
    ]
