# Generated by Django 2.2 on 2022-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0007_acssensor_max_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='scaling',
            field=models.IntegerField(blank=True, default=1, verbose_name='Масштабирование'),
        ),
    ]
