# Generated by Django 2.2 on 2022-10-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0008_acssensor_scaling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='scaling',
            field=models.IntegerField(),
        ),
    ]
