# Generated by Django 2.2 on 2022-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0009_auto_20221024_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='scaling2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
