# Generated by Django 2.2 on 2022-10-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0010_acssensor_scaling2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acssensor',
            name='scaling2',
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='scaling',
            field=models.IntegerField(default=0, verbose_name='Мастштабирование'),
        ),
    ]
