# Generated by Django 2.2 on 2022-10-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0011_auto_20221024_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='ratio',
            field=models.IntegerField(default=0, verbose_name='Мастштабирование'),
        ),
    ]
