# Generated by Django 2.2 on 2022-10-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0012_acssensor_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acssensor',
            name='scaling',
        ),
    ]
