# Generated by Django 2.2 on 2022-10-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0013_remove_acssensor_scaling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='ratio',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Показание'),
        ),
    ]
