# Generated by Django 2.2 on 2022-10-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0014_auto_20221024_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='ratio',
            field=models.IntegerField(blank=True, default=1, verbose_name='Масштабирование'),
        ),
    ]
