# Generated by Django 2.2 on 2022-10-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0016_acssensor_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='critical_value_from',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Критический показатель от'),
        ),
        migrations.AddField(
            model_name='acssensor',
            name='critical_value_to',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Критический показатель до'),
        ),
        migrations.AddField(
            model_name='acssensor',
            name='danger_value_from',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Показатель опасности от'),
        ),
        migrations.AddField(
            model_name='acssensor',
            name='danger_value_to',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Показатель опасности до'),
        ),
        migrations.AddField(
            model_name='acssensor',
            name='norm_value_from',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Показатель нормы от'),
        ),
        migrations.AddField(
            model_name='acssensor',
            name='norm_value_to',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Показатель нормы до'),
        ),
        migrations.AddField(
            model_name='acssensor',
            name='scale',
            field=models.CharField(default='0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0', max_length=250, verbose_name='Шкала датчика'),
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='step',
            field=models.FloatField(blank=True, default=0.01, verbose_name='Шаг'),
        ),
    ]
