# Generated by Django 2.2 on 2022-10-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0017_auto_20221024_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='danger_value_to',
            field=models.FloatField(blank=True, default=0.0, help_text='Показатель опасности до', verbose_name='Показатель опасности до'),
        ),
    ]
