# Generated by Django 2.2 on 2022-10-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0018_auto_20221024_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='critical_value_from',
            field=models.FloatField(default=0.0, verbose_name='Критический показатель от'),
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='critical_value_to',
            field=models.FloatField(default=0.0, verbose_name='Критический показатель до'),
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='danger_value_from',
            field=models.FloatField(default=0.0, verbose_name='Показатель опасности от'),
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='danger_value_to',
            field=models.FloatField(default=0.0, help_text='Показатель опасности до', verbose_name='Показатель опасности до'),
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='norm_value_from',
            field=models.FloatField(default=0.0, verbose_name='Показатель нормы от'),
        ),
        migrations.AlterField(
            model_name='acssensor',
            name='norm_value_to',
            field=models.FloatField(default=0.0, verbose_name='Показатель нормы до'),
        ),
    ]
