# Generated by Django 2.2 on 2022-10-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0019_auto_20221024_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='step',
            field=models.FloatField(default=0.01, verbose_name='Шаг'),
        ),
    ]
