# Generated by Django 2.2 on 2022-10-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0020_auto_20221024_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acssensor',
            name='step',
        ),
    ]
