# Generated by Django 2.2.4 on 2022-11-01 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0021_remove_acssensor_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='connect_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Последнее подключение'),
        ),
    ]
