# Generated by Django 2.2.4 on 2022-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0022_acssensor_connect_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acsindicators',
            index=models.Index(fields=['sensor'], name='acs_acsindi_sensor__7c29a4_idx'),
        ),
    ]
