# Generated by Django 2.2.4 on 2022-11-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221123_0925'),
        ('acs', '0023_auto_20221110_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssensor',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Zone', verbose_name='Зона'),
        ),
        migrations.AlterField(
            model_name='acsindicators',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acs.AcsSensor', verbose_name='Датчик'),
        ),
    ]
