# Generated by Django 2.2.4 on 2023-02-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0025_acsindicators_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acsindicators',
            index=models.Index(fields=['type'], name='acs_acsindi_type_d3dab2_idx'),
        ),
    ]
