# Generated by Django 2.2.4 on 2023-02-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0028_auto_20230211_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acssensor',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Zone', verbose_name='Зона'),
        ),
    ]
