# Generated by Django 2.2.4 on 2023-02-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0029_auto_20230211_1346'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acsindicators',
            name='acs_acsindi_sensor__7c29a4_idx',
        ),
    ]
