# Generated by Django 2.2.4 on 2023-02-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0030_auto_20230228_1454'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acsindicators',
            index=models.Index(fields=['date_time'], name='acs_acsindi_date_ti_fc6d0c_idx'),
        ),
    ]
