# Generated by Django 2.2.4 on 2023-02-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0031_auto_20230228_1838'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acsindicators',
            name='acs_acsindi_date_ti_54a518_idx',
        ),
        migrations.AddIndex(
            model_name='acsindicators',
            index=models.Index(fields=['sensor', 'date_time'], name='acs_acsindi_sensor__d776f8_idx'),
        ),
    ]
