# Generated by Django 2.2.4 on 2023-02-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0032_auto_20230228_1858'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acsindicators',
            name='acs_acsindi_date_ti_fc6d0c_idx',
        ),
    ]
