# Generated by Django 2.2 on 2022-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=60, verbose_name='Наименование')),
                ('TimeZone', models.IntegerField(choices=[(2, 'UTC+02 (Калининградское время)'), (3, 'UTC+03 (Московское время)'), (4, 'UTC+04 (Самарское время)'), (5, 'UTC+05 (Екатеринбургское время)'), (6, 'UTC+06 (Омское время)'), (7, 'UTC+07 (Красноярское время)'), (8, 'UTC+08 (Иркутское время)'), (9, 'UTC+09 (Якутское время)'), (10, 'UTC+10 (Владивостокское время)'), (11, 'UTC+11 (Среднеколымское время)'), (12, 'UTC+12 (Камчатское время)')], default=3, verbose_name='Часовой пояс')),
                ('latitude', models.CharField(blank=True, default=' ', max_length=60, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, default=' ', max_length=60, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='catalog_loc_name_bbae45_idx'),
        ),
    ]
