# Generated by Django 2.2 on 2022-10-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=60, verbose_name='Наименование')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Location', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'зона',
                'verbose_name_plural': 'зоны',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['location'], name='catalog_zon_locatio_3e96eb_idx'),
        ),
    ]
