# Generated by Django 2.2 on 2023-02-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221123_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='department',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
    ]
