# Generated by Django 2.2 on 2023-02-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20230228_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='uid',
            field=models.CharField(blank=True, help_text='uid', max_length=45, verbose_name='uid'),
        ),
    ]
