# Generated by Django 2.2 on 2023-02-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_worker_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='uid',
            field=models.CharField(blank=True, help_text='uid', max_length=36, verbose_name='uid'),
        ),
    ]
