# Generated by Django 2.2.4 on 2023-03-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20230228_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Position', verbose_name='Должность'),
        ),
    ]
