# Generated by Django 2.2.4 on 2022-12-05 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_auto_20221123_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='FpsSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default=' ', max_length=160, verbose_name='ТЭГ')),
                ('name', models.CharField(default=' ', max_length=160, verbose_name='Наименование')),
                ('critical_value', models.FloatField(default=0.0, verbose_name='Критически допустимое значение')),
                ('critical_type', models.CharField(choices=[('max', 'Максимальный'), ('min', 'Минимальный')], default=1, max_length=3, verbose_name='Тип')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('ratio', models.IntegerField(blank=True, default=1, verbose_name='Масштабирование')),
                ('value', models.FloatField(blank=True, default=0.0, verbose_name='Показание')),
                ('max_value', models.FloatField(blank=True, default=0.0, verbose_name='Максимальное значение')),
                ('unit', models.CharField(default=' ', max_length=10, verbose_name='Ед.измерения')),
                ('comments', models.TextField(blank=True, default=' ', max_length=1001, verbose_name='Комментарий')),
                ('scale', models.CharField(default='0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0', max_length=250, verbose_name='Шкала датчика')),
                ('norm_value_from', models.FloatField(default=0.0, verbose_name='Показатель нормы от')),
                ('norm_value_to', models.FloatField(default=0.0, verbose_name='Показатель нормы до')),
                ('danger_value_from', models.FloatField(default=0.0, verbose_name='Показатель опасности от')),
                ('danger_value_to', models.FloatField(default=0.0, help_text='Показатель опасности до', verbose_name='Показатель опасности до')),
                ('critical_value_from', models.FloatField(default=0.0, verbose_name='Критический показатель от')),
                ('critical_value_to', models.FloatField(default=0.0, verbose_name='Критический показатель до')),
                ('connect_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Последнее подключение')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'датчик',
                'verbose_name_plural': 'датчики',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FpsIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Время показаний')),
                ('value', models.FloatField(default=0.0, verbose_name='Показание')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fps.FpsSensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'показание датчика',
                'verbose_name_plural': 'показания датчиков',
                'ordering': ('sensor',),
            },
        ),
        migrations.AddIndex(
            model_name='fpssensor',
            index=models.Index(fields=['tag'], name='fps_fpssens_tag_367731_idx'),
        ),
        migrations.AddIndex(
            model_name='fpssensor',
            index=models.Index(fields=['name'], name='fps_fpssens_name_ee2a82_idx'),
        ),
        migrations.AddIndex(
            model_name='fpssensor',
            index=models.Index(fields=['tag', 'name'], name='fps_fpssens_tag_f13ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='fpsindicators',
            index=models.Index(fields=['sensor'], name='fps_fpsindi_sensor__2ef9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='fpsindicators',
            index=models.Index(fields=['date_time', 'sensor'], name='fps_fpsindi_date_ti_846657_idx'),
        ),
    ]
