# Generated by Django 2.2.4 on 2023-02-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fps', '0002_auto_20230212_1832'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fpsindicators',
            name='fps_fpsindi_sensor__2ef9d8_idx',
        ),
    ]
