# Generated by Django 2.2.4 on 2022-09-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMfsb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='Время значения')),
                ('name', models.CharField(blank=True, default=' ', max_length=150, null=True, verbose_name='ТЭГ')),
                ('values', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('check', models.BooleanField(blank=True, default=True, verbose_name='Активная отметка')),
            ],
            options={
                'verbose_name': 'показатель датчика',
                'verbose_name_plural': 'показатели датчиков',
            },
        ),
        migrations.AddIndex(
            model_name='datamfsb',
            index=models.Index(fields=['date', 'name'], name='main_datamf_date_6042f4_idx'),
        ),
        migrations.AddIndex(
            model_name='datamfsb',
            index=models.Index(fields=['name'], name='main_datamf_name_edf405_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datamfsb',
            unique_together={('name', 'date')},
        ),
    ]
