# Generated by Django 2.2.4 on 2022-09-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamfsb',
            unique_together=set(),
        ),
    ]
