# Generated by Django 2.2.4 on 2022-09-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220904_1229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamfsb',
            unique_together={('name', 'date')},
        ),
    ]
