# Generated by Django 2.2.4 on 2022-12-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220904_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMfsbSkada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='Время значения')),
                ('name', models.CharField(blank=True, default=' ', max_length=150, null=True, verbose_name='ТЭГ')),
                ('values', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('check', models.BooleanField(blank=True, default=True, verbose_name='Активная отметка')),
            ],
            options={
                'verbose_name': 'показатель датчика SKADA',
                'verbose_name_plural': 'показатели датчиков SKADA',
            },
        ),
        migrations.AddIndex(
            model_name='datamfsbskada',
            index=models.Index(fields=['date', 'name'], name='main_datamf_date_7ed148_idx'),
        ),
        migrations.AddIndex(
            model_name='datamfsbskada',
            index=models.Index(fields=['name'], name='main_datamf_name_975b1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datamfsbskada',
            unique_together={('name', 'date')},
        ),
    ]
