# Generated by Django 2.2.4 on 2023-01-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221205_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMfsbPpz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='Время значения')),
                ('name', models.CharField(blank=True, default=' ', max_length=450, null=True, verbose_name='ТЭГ')),
                ('code', models.IntegerField(blank=True, default=1, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'показатель противопожарной защиты',
                'verbose_name_plural': 'показатель противопожарной защиты',
            },
        ),
        migrations.CreateModel(
            name='DataMfsbSkpv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='Время значения')),
                ('name', models.CharField(blank=True, default=' ', max_length=450, null=True, verbose_name='ТЭГ')),
                ('values', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('check', models.BooleanField(blank=True, default=True, verbose_name='Активная отметка')),
            ],
            options={
                'verbose_name': 'показатель датчика пожарного водоснобжения',
                'verbose_name_plural': 'показатели датчиков пожарного водоснобжения',
            },
        ),
        migrations.AddIndex(
            model_name='datamfsbskpv',
            index=models.Index(fields=['date', 'name'], name='main_datamf_date_2dc4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='datamfsbskpv',
            index=models.Index(fields=['name'], name='main_datamf_name_1b2860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datamfsbskpv',
            unique_together={('name', 'date')},
        ),
        migrations.AddIndex(
            model_name='datamfsbppz',
            index=models.Index(fields=['date', 'name'], name='main_datamf_date_4a843f_idx'),
        ),
        migrations.AddIndex(
            model_name='datamfsbppz',
            index=models.Index(fields=['name'], name='main_datamf_name_64a7b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datamfsbppz',
            unique_together={('name', 'date')},
        ),
    ]
