# Generated by Django 2.2.4 on 2023-01-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230119_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamfsbppz',
            name='check',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активная отметка'),
        ),
    ]
