# Generated by Django 2.2.4 on 2023-01-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_datamfsbppz_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamfsbskpv',
            options={'verbose_name': 'показатель датчика пожарного водоснабжения', 'verbose_name_plural': 'показатели датчиков пожарного водоснабжения'},
        ),
    ]
