# Generated by Django 2.2.4 on 2023-01-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230119_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamfsb',
            options={'verbose_name': 'показатель датчика АГК И и КЗ', 'verbose_name_plural': 'показатели датчиков АГК И и КЗ'},
        ),
    ]
