# Generated by Django 2.2.4 on 2023-02-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230119_1837'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datamfsb',
            index=models.Index(fields=['name', 'check'], name='main_datamf_name_9a3f8e_idx'),
        ),
    ]
