# Generated by Django 2.2 on 2023-05-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230220_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='Время значения')),
                ('name', models.CharField(blank=True, default=' ', max_length=160, null=True, verbose_name='ТЭГ')),
                ('values', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Значение')),
                ('check', models.BooleanField(blank=True, default=True, verbose_name='Активная отметка')),
            ],
            options={
                'verbose_name': 'показатель КТП',
                'verbose_name_plural': 'показатели КТП',
            },
        ),
        migrations.AddIndex(
            model_name='dataktp',
            index=models.Index(fields=['date', 'name'], name='main_datakt_date_dd7d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='dataktp',
            index=models.Index(fields=['name'], name='main_datakt_name_0b7e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='dataktp',
            index=models.Index(fields=['name', 'check'], name='main_datakt_name_e93fcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataktp',
            unique_together={('name', 'date')},
        ),
    ]
