# Generated by Django 2.2 on 2023-05-22 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ktpsensor',
            name='serial',
        ),
    ]
