# Generated by Django 2.2 on 2023-05-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0002_remove_ktpsensor_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KtpIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Время показаний')),
                ('value', models.CharField(default=' ', max_length=50, verbose_name='Показание')),
                ('ismarked', models.BooleanField(blank=True, default=False, verbose_name='Пометка')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktp.KtpSensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'показание датчика',
                'verbose_name_plural': 'показания датчиков',
                'ordering': ('sensor',),
            },
        ),
        migrations.AddIndex(
            model_name='ktpindicators',
            index=models.Index(fields=['sensor', 'date_time'], name='ktp_ktpindi_sensor__e095ed_idx'),
        ),
    ]
