# Generated by Django 2.2 on 2023-05-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0003_auto_20230522_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktpsensor',
            name='serial',
            field=models.CharField(default=' ', max_length=5, verbose_name='Серийный номер'),
        ),
    ]
