# Generated by Django 2.2 on 2023-05-23 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0005_auto_20230523_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ktpindicators',
            name='ismarked',
        ),
    ]
